### ISSUE TITLE
More claim/chunk settings

### ISSUE THREAD

**Issue by pleasepoggitwork** [DaPigGuy/PiggyFactions#10]
Please make sure your issue complies with these guidelines:
- * [X] Idea must have not been suggested previously
- * [X] Be detailed on what you want & make sure the idea is plausible

### Description

Make chunks 1 chunk or make claim size customize able, then add a max claims per faction option with each claim costing more power.
And also maybe add a /seeclaim command  so faction members can see the outline of their faction claim (if claims are next to each other the border would merge), this feature working like seechunk.
### Extra Information

**Comment by pleasepoggitwork** [comment]
Claims*

**Comment by DaPigGuy** [comment]
1. Claims are 1 chunk wide
2.  Maximum amount of claims per faction is configurable
3. seechunk exists as a subcommand of /f
