### ISSUE TITLE
The Piggy faction plugin dosen t save the factions for players

### ISSUE THREAD

**Issue by Gezou** [DaPigGuy/PiggyFactions#101]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyFactions
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. Create a faction 
2. Then leave and join again

### Crashdump
Link:  https://pastebin.com/e56RVMTs

### Extra Information

**Comment by Aericio** [comment]
I'm not sure what happened to your sql file, but just go to plugin_data and delete `factions.sql`

If you have data in it, then try to manually recover the sql file somehow. I cannot help you with that.
