### ISSUE TITLE
Problem of claim in protected areas

### ISSUE THREAD

**Issue by CapybaraPin** [DaPigGuy/PiggyFactions#105]
Hello, I have encountered a bug that can be quite annoying especially for protected areas like spawn. 

**- Problem encountered:** 

It is possible to claim on the areas of a spawn (or the area stops at layer 255) for example. So the player doesn't have to go to layer 256 anymore and he can claim over the spawn. This is quite annoying. 

**- What should happen normally:**

To solve this problem, when an area is at layer 255, it should be automatically impossible to make claims on it. 

**- Steps to Reproduce the Issue:**

Simply move to the top of the 255 layer and do `/f claim`

**- Server info:**

```
[Server thread/INFO]: [PiggyFactions] Showing debug info...
-- PLUGIN INFO --
NAME: PiggyFactions
VERSION: 1.2.0
VIA: BUILD #136
DATABASE: mysql
ECONOMY: DISABLED
FORMS: ENABLED
-- PMMP INFO --
NAME: PocketMine-MP
VERSION: 3.25.4
GIT COMMIT: 7306a2d939105d8d91b4180de9aec42a31d9570f
-- MC INFO --
VERSION: 1.17.40
PROTOCOL: 471
-- SYSTEM INFO --
OS TYPE: Linux, linux
OS VERSION: #1 SMP Debian 4.19.194-3 (2021-07-18)
PHP VERSION: 8.0.12
-- PLUGINS --
WorldGuard v1.1.95, PiggyFactions v1.2.0, 
```

**Comment by Aericio** [comment]
Just to confirm, you're saying to disable claiming if the user is at y=255?

**Comment by CapybaraPin** [comment]
That's it indeed, to avoid that it can claim over the protected areas.

**Comment by Aericio** [comment]
Are "protected areas" referring to WorldGuard?

**Comment by CapybaraPin** [comment]
Yes

**Comment by CapybaraPin** [comment]
@Aericio Is there a solution to the problem?

**Comment by Aericio** [comment]
Yes, but I don't have time right now.

**Comment by Aericio** [comment]
Also, couldn't you just like, make the area one level higher on WorldGuard?

**Comment by DaPigGuy** [comment]
You can create a faction with the safezone flag & claim over the spawn area.
