### ISSUE TITLE
Unable to eat food

### ISSUE THREAD

**Issue by Ember61** [DaPigGuy/PiggyFactions#11]
### Issue Description

- Expected result: What were you expecting to happen?
I was expecting an increase in my hunger bar
- Actual result: What actually happened?
There is a bug which prevents all players from eating any type of food
#### Steps to Reproduce the Issue
1. Give yourself any sort of food eg.carrots
2.Try to eat it

### OS and Versions

* PocketMine-MP:3.12.0
* PiggyFactions:1.0.1
* PHP:7.4.5
* Server OS:Windows

### Extra Information

**Comment by Heisenburger69** [comment]
This is caused by cancelling interact event, maybe don't cancel it if the player has an item that can be consumed

**Comment by Ember61** [comment]
> This is caused by cancelling interact event, maybe don't cancel it if the player has an item that can be consumed

how do i do that?

**Comment by Ember61** [comment]
hmm
The issue somehow got fixed after i reinstalled the plugin

**Comment by Ember61** [comment]
The issue somehow got resolved for a while but it came back

**Comment by Aericio** [comment]
Next time, you can just re-open this issue instead of creating a new one.
