### ISSUE TITLE
crash when promoting player with space in name

### ISSUE THREAD

**Issue by logannn61** [DaPigGuy/PiggyFactions#117]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyFactions
- * [ ] Have a detailed title.

### Issue Description

- Expected result: player to be promoted and server not crash
- Actual result: server crashed

#### Steps to Reproduce the Issue
1. Load server with piggy factions
2. Promote a player with a space in their name

### Crashdump
Link: https://crash.pmmp.io/view/6458226

### This is without using " " it would probably work with them but still someone on my server figured this out and now they can crash the server whenever they feel like it by typing promoting a player with a space in name

**Comment by logannn61** [comment]
Correction i think the crash happens when you promote or demote someone that is offline

**Comment by Aericio** [comment]
Should be fixed in #125
