### ISSUE TITLE
Being able to put § in faction name

### ISSUE THREAD

**Issue by logannn61** [DaPigGuy/PiggyFactions#119]
people can put a § to change the colours and text of their faction name which causes a lot of problems such as people being able to put §k which makes the faction leader board unreadable for every faction below them.

**Comment by Aericio** [comment]
add `{RESET}` in the english.yml in the affected commands

https://github.com/DaPigGuy/PiggyFactions/blob/master/resources/languages/english.yml#L148-L154
```diff
- online: "{GOLD}#{RANK} {RELATIONCOLOR}{FACTION}{GOLD} -{YELLOW} {ONLINE}"
+ online: "{GOLD}#{RANK} {RELATIONCOLOR}{FACTION}{GOLD}{RESET} -{YELLOW} {ONLINE}"
```

**Comment by Aericio** [comment]
can make it so we strip all text formatting from faction name in code, but for now that is easiest solution.

**Comment by logannn61** [comment]
okay thank you
