### ISSUE TITLE
A faction cap

### ISSUE THREAD

**Issue by PsychoPE** [DaPigGuy/PiggyFactions#13]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

An area where a faction has to capture then they can gain power every 30 or so seconds that they have that area captured for.

Potential commands
/f pos1
/f pos2
/f cap gain 10 (this is how much power they gain

Time and how much power they gain could also be configured in the config rather than commands also how long it takes the capture the cap
### Extra Information

**Comment by DaPigGuy** [comment]
This feature is something we do not believe should be included in the core plugin. If a plugin developer would like to do this externally, they may do so.
