### ISSUE TITLE
Running PHP 8.1 causes plugin to crash

### ISSUE THREAD

**Issue by dadodasyra** [DaPigGuy/PiggyFactions#130]
I was sure that merging #128  was a bad idea. And my thoughts were correct, the plugin does not even boots up.
"withdraw" is registered 2 times in FactionCommand. And I guess it's not the only issue with this PR

**Comment by Aericio** [comment]
I had tested it, but did not test it with economy features enabled. I'll check later.

**Comment by Aericio** [comment]
Other changes seem to be working fine, though.

**Comment by Aericio** [comment]
It seems fine to me. Faction commands are also working properly.

![image](https://github.com/DaPigGuy/PiggyFactions/assets/16523741/3725b41d-7303-4e2e-8a51-be139927e7a6)

**Comment by Aericio** [comment]
Working now after updating virions.

![image](https://github.com/DaPigGuy/PiggyFactions/assets/16523741/42381273-7831-4339-a078-3c468649a8ad)
