### ISSUE TITLE
PM5

### ISSUE THREAD

**Issue by dadodasyra** [DaPigGuy/PiggyFactions#131]
Any plan for a PM5 version ? Now that PM5 is an official thing.

**Comment by Aericio** [comment]
I plan to, but no specific date on when. I've not looked at the changelog for PM5.

Contributions, from anyone, are appreciated.

**Comment by RemBog** [comment]
Please do as soon as possible @Aericio

**Comment by Aericio** [comment]
Now available in v2.1.0
