### ISSUE TITLE
/op Command

### ISSUE THREAD

**Issue by BlueKill456** [DaPigGuy/PiggyFactions#135]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyFactions
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ... execute /op player in console
2. ... Not permission

### Extra Information

**Comment by Aericio** [comment]
Report this at https://github.com/pmmp/PocketMine-MP/issues
