### ISSUE TITLE
Unable to eat food

### ISSUE THREAD

**Issue by Ember61** [DaPigGuy/PiggyFactions#14]
### Issue Description 

- Expected result: What were you expecting to happen?
Eat the food
- Actual result: What actually happened?
Food was not consumed

#### Steps to Reproduce the Issue
1.Switch to gamemode 0
2. Try to eat any sort of food eg.. carrots

### OS and Versions

* PocketMine-MP:3.12.0
* PiggyFactions:1.0.1
* PHP:7.4.5
* Server OS:Windows

The issue somehow resolved for a while but it suddenly came back

**Comment by DaPigGuy** [comment]
We were not able to reproduce the issue in a claim with interact permissions off for non-members.

**Comment by Aericio** [comment]
Could you show the output of `/pl`?

**Comment by Ember61** [comment]
![Screenshot_2020-05-08-11-34-04-916~2](https://user-images.githubusercontent.com/64958664/81376076-6d7b4e80-9120-11ea-971c-cc84f52f61d3.jpeg)

**Comment by Ember61** [comment]
I don't think the title matches the issue because i'm also facing the issue in wilderness

**Comment by Aericio** [comment]
Try removing EssentialsPE

**Comment by Ember61** [comment]
I did but the issue still persists

**Comment by Aericio** [comment]
My second guess would be WorldGuard, try removing that and try again.

**Comment by Ember61** [comment]
i did that yesterday

**Comment by Aericio** [comment]
What's your client OS?

**Comment by Ember61** [comment]
I'm hosting it on my phone right now but i tested it on my pc too

**Comment by Aericio** [comment]
Android? We'll do some testing, then. 

Did you already try removing all plugins besides PiggyFactions?

**Comment by Ember61** [comment]
No,I'll try that now

**Comment by Ember61** [comment]
I deleted all other plugins but still the same

**Comment by Aericio** [comment]
We'll investigate.

**Comment by Ember61** [comment]
Okay

**Comment by DaPigGuy** [comment]
We are still unable to reproduce the issue. Please try updating your PiggyFactions to 1.0.2

**Comment by Aericio** [comment]
Duplicate of #11
