### ISSUE TITLE
When I use /f create the server crashes

### ISSUE THREAD

**Issue by Andyluish** [DaPigGuy/PiggyFactions#140]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyFactions
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### Crashdump
Link: 

### Extra Information

**Comment by Aericio** [comment]
Not enough information.
