### ISSUE TITLE
Economy API Support

### ISSUE THREAD

**Issue by MyBrainCellz** [DaPigGuy/PiggyFactions#15]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description
I think the plugin should support EconomyAPI so you can add money to your faction. For example, you could use /f deposit to add money to the faction and /f withdraw vice versa. You could use this money to claim or have a leaderboard of the richest factions.

### Extra Information

**Comment by Thunder33345** [comment]
leaderboard of riches sounds like meh justification to implement a f bank 
yes lets make faction bank just so everyone can clump thier money together to show who's the riches
totally good and fun gameplay here
totally worth our effort to go out of way for this

what i am trying to say is, maybe with more reason and justification, this can be considered

**Comment by Aericio** [comment]
Some people wanted `/f claim` to use money faction bank.

**Comment by Heisenburger69** [comment]
+ Extensions could be made for like fac upgrades and stuff using the f bank
