### ISSUE TITLE
Kicks me from the game when i try to open a chest from another faction property

### ISSUE THREAD

**Issue by Ember61** [DaPigGuy/PiggyFactions#16]
### Issue Description

- Expected result: What were you expecting to happen?
I was expecting for me to either open the chest or the plugin to prevent me from doing so.
- Actual result: What actually happened?
I got an "Internal Exception Error"
#### Steps to Reproduce the Issue
1. Go to admin mode
2.Make a faction
3.claim a chunk and place a chest in it.
Leave the faction and try to open the chest

### OS and Versions

* PocketMine-MP:3.12.0
* PiggyFactions:1.0.1
* PHP:7.4.5
* Server OS:Windows

**Comment by DaPigGuy** [comment]
Unable to reproduce issue. Please screenshot or copy & paste any errors in console.

**Comment by Ember61** [comment]
Could i dm you the console log 
i'm afraid of getting my ip leaked
