### ISSUE TITLE
Claim display in actionbar(popup)

### ISSUE THREAD

**Issue by minijaham** [DaPigGuy/PiggyFactions#17]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

To be very honest, doing /f map every time kind of sucks. So when a player walks into a claim(counts for the players in that faction too), it shows a message(keeps showing until you get out of the claim) in the actionbar(pop up) saying something like "Area claimed by: {faction}"
### Extra Information
No extra information

**Comment by DaPigGuy** [comment]
Faction of the territory you're walking into is already displayed as a title, unless you are still within that faction's territory.
