### ISSUE TITLE
How do I configure claim worlds?

### ISSUE THREAD

**Issue by minijaham** [DaPigGuy/PiggyFactions#18]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description
How can I configure the claim world?
I have not been able to figure out where I could configure the worlds that claiming is enabled...

### Extra Information
None

**Comment by DaPigGuy** [comment]
All worlds allow claiming by default. You can blacklist certain worlds from claiming within the config.
