### ISSUE TITLE
adding customizable faction chat messages (rank tags etc)

### ISSUE THREAD

**Issue by NidPlays** [DaPigGuy/PiggyFactions#2]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

Option to add custom faction chat messages like {ranksymbol} {rankname} etc in /f c or /f ac
### Extra Information

**Comment by Thunder33345** [comment]
do you mean custom fac/ally chat formatting?
maybe we can just base off hrk chat? or should we do our own thingy?
https://github.com/DaPigGuy/PiggyFactions/blob/master/resources/config.yml#L50-L56
