### ISSUE TITLE
Spawner Value

### ISSUE THREAD

**Issue by KareemDoesMc** [DaPigGuy/PiggyFactions#20]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description

Ok hopefully this wasn't suggested but...
I think you should show a factions money on f top. But the money should be based on spawners you have in the claims and maybe the money you have.
### Extra Information

**Comment by Thunder33345** [comment]
related to #4

**Comment by Aericio** [comment]
Merging.
