### ISSUE TITLE
Chunk Claims

### ISSUE THREAD

**Issue by KareemDoesMc** [DaPigGuy/PiggyFactions#23]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

You should add chunk claims for example we can do /f claim 2,10,20 etc
### Extra Information

**Comment by DaPigGuy** [comment]
1.0.3 introduces /f claim circle & /f claim square
