### ISSUE TITLE
Hierarchy Support

### ISSUE THREAD

**Issue by arclegrandroi** [DaPigGuy/PiggyFactions#24]
Can you add suport for this plugin : https://github.com/CortexPE/Hierarchy

And can y have you comunitis discord(or you don't have one?)?

**Comment by Aericio** [comment]
Hierarchy/HRKChat support has already been added: https://github.com/DaPigGuy/PiggyFactions#hrkchat-tags

Discord: https://discord.com/invite/qmnDsSD
