### ISSUE TITLE
PureChat PR10

### ISSUE THREAD

**Issue by ConstructStudios** [DaPigGuy/PiggyFactions#27]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyFactions
- * [x] Have a detailed title.

After installing PR10 now my ranks dont show and all i see is my name in all white

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### OS and Versions

* PocketMine-MP:
* PiggyFactions:
* PHP:
* Server OS:

### Extra Information

**Comment by Aericio** [comment]
Please upload your PureChat configuration to https://hastebin.com/.

**Comment by ConstructStudios** [comment]
- https://hastebin.com/harejahemu.bash

So i saw that faction name was not showing in chat id look for the issue in the "Issue" section and swap to PR10, after swapping the ranks dont show and turn everything white with no ranks at all.

**Comment by Aericio** [comment]
You messed up your configuration, missing `" "`.
Paste your PureChat configuration into http://www.yamllint.com/ and press "Go", then copy the output.

**Comment by ConstructStudios** [comment]
it say "Valid YAML!" so where am i missing the (" ")?

**Comment by ConstructStudios** [comment]
@Aericio

**Comment by Aericio** [comment]
If you compare the hastebin contents to the output of yamllint, you are *very obviously* missing quotes.
![image](https://user-images.githubusercontent.com/16523741/81493891-02289e00-9240-11ea-8c9d-bf55b8f03eec.png)
It says "Valid YAML!" because running it through yamllint will fix minor mistakes.

**Comment by ConstructStudios** [comment]
Thanks for clarification, appreciated.
