### ISSUE TITLE
Scoreboard support

### ISSUE THREAD

**Issue by PsychoPE** [DaPigGuy/PiggyFactions#29]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

Support for score hud by JackMD so we can show faction name, faction power, faction rank etc 
### Extra Information

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyFactions#scorehud-addon

**Comment by PsychoPE** [comment]
Where can I see all the addons for if you add anymore in the future

**Comment by Aericio** [comment]
It will also be in the readme.
