### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by KareemDoesMc** [DaPigGuy/PiggyFactions#30]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyFactions
- * [ ] Have a detailed title.

Link to crashdump: 
https://hastebin.com/miwamiheza.cs

### Extra Information

**Comment by DaPigGuy** [comment]
Download from Poggit.
