### ISSUE TITLE
Flight in own faction claims

### ISSUE THREAD

**Issue by KauaMCPE** [DaPigGuy/PiggyFactions#31]
Add in the /f fly plugin that it is possible to fly on the ground of your faction with permission!!!

**Comment by KauaMCPE** [comment]
Upon leaving their territory the player will lose the /f fly, a message will appear to him that is off the ground dominated by his faction and will instantly disable.

**Comment by Aericio** [comment]
Added in commit https://github.com/DaPigGuy/PiggyFactions/commit/b4806f44f86fbc28edf3c0ec09030f3903825652

**Comment by KauaMCPE** [comment]
Please add when a base is attacked in the claim when a tnt activated in your territory appears on top of the hotbar a message saying that the base is being attacked and to leave this message has a time of 5 minutes, disable everything will not be able to remove spawners, chest and not even the /f fly because disable it also.

**Comment by Aericio** [comment]
An external plugin can do that instead. This won't be added to the main plugin.
