### ISSUE TITLE
Flight configuration in config

### ISSUE THREAD

**Issue by HugoLeBoss91** [DaPigGuy/PiggyFactions#38]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description
Added the possibility to deactivate / f fly in config.yml
### Extra Information

**Comment by Thunder33345** [comment]
duplicate of #31

**Comment by Thunder33345** [comment]
oops read it wrongly

**Comment by DaPigGuy** [comment]
If using PurePerms  or Hierarchy, you can remove the permission for /f fly from players.
