### ISSUE TITLE
f disband for OP

### ISSUE THREAD

**Issue by HugoLeBoss91** [DaPigGuy/PiggyFactions#39]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description
Add the command / f disband {faction} for the OP.
### Extra Information

**Comment by Thunder33345** [comment]
you can /f admin disband
unless that command dosent support disband

**Comment by Aericio** [comment]
You will need to do: `/f admin` -> `/f join <faction>` -> `/f disband`. An easier way will be added, but it can be done like this for now.

**Comment by Thunder33345** [comment]
we need better subcmd lib
to handle admin disband
like admin mode can /f admin disband (name)

**Comment by jaylac2000** [comment]
i vote add /f disband <faction> for ops. becuase why would they wanna leave their own faction to delete lets say a hackers faction...
