### ISSUE TITLE
Factions Leaderboard Floating Text

### ISSUE THREAD

**Issue by PsychoPE** [DaPigGuy/PiggyFactions#4]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

A floating text that we can place any where with a command or in config it displayed the top 10 factions along with their power

Text example:

Top Factions
1) Psychos 9547
2) Trident 8563

And the colours can be formatted in config 

#20: `/f top` money based on spawners in faction claims + factions bank.

### Extra Information

**Comment by Thunder33345** [comment]
shouldnt we leave this responsibility as a "piggy fac extension"?

**Comment by pleasepoggitwork** [comment]
I feel like topfactions shouldnt be based on strength because of the fact that the faction that has the most players (at m ax strength) will be top. It should be based on /f balance OR a extension to burger spawenrs.

**Comment by Thunder33345** [comment]
this is why honestly we shouldnt just make everything into piggyfactions so we can let owners customize the included extensions
#15 maybe but it still needs more justification IMO

**Comment by PsychoPE** [comment]
I mean it’s a suggestions tab meaning he can do what he wants with it he can make it an extension he can put it into the actual plugin or he can do. I thing with it that’s the whole point of a suggestion

**Comment by Thunder33345** [comment]
yes
