### ISSUE TITLE
Things i would love to Get Put in.

### ISSUE THREAD

**Issue by EarthCraftOfficial** [DaPigGuy/PiggyFactions#43]
1. be Able to Increase Claim size so like 128x128, 2. How to get Strength, 3. Something like Purechat, 4. Something is broken with the Power so its like .6666666666 and stuff its quite annoying, Check out Factions pro on its yml

**Comment by DaPigGuy** [comment]
1. No. Associating claims by something other than chunks will cause a complicated mess.
2. Power is given over time as you are online
3. PureChat PR #10 adds PiggyFactions support
4. Where?

**Comment by Thunter1** [comment]
> 1. No. Associating claims by something other than chunks will cause a complicated mess.
> 2. Power is given over time as you are online
> 3. PureChat PR #10 adds PiggyFactions support
> 4. Where?

^^^everywhere

**Comment by Aericio** [comment]
Fixed in #44
