### ISSUE TITLE
Make Faction Power an int.

### ISSUE THREAD

**Issue by ItsMax123** [DaPigGuy/PiggyFactions#44]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

Make Faction power an int or something to make it not look like this: 1.3333333333333333333333

### Extra Information

**Comment by DaPigGuy** [comment]
The GitHub gist for ScoreHUD addon has also been updated to round the displayed power.
