### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jaylac2000** [DaPigGuy/PiggyFactions#45]
make /f fly 

default: true 

to 

default: false

because this is a great paid rank perk

**Comment by Aericio** [comment]
If you're using PurePerms, set the permission to `-piggyfactions.command.faction.fly`

**Comment by jaylac2000** [comment]
im aware how to set permissions...... but you have it set to true. it should be false because it gives the server owner the final decision weather to let people fly or certain ranks to fly

**Comment by Aericio** [comment]
It's a default factions permission. If the server owner doesn't want that, then the server owner should deny that permission themselves.

**Comment by jaylac2000** [comment]
and how do you deny a perm without forking and disabling it my self

**Comment by Aericio** [comment]
Did you not read what I just said?
> If you're using PurePerms, set the permission to `-piggyfactions.command.faction.fly`

**Comment by Aericio** [comment]
Your configuration listing would look like:
`- -piggyfactions.command.faction.fly`

**Comment by jaylac2000** [comment]
ok ty
