### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by KauaMCPE** [DaPigGuy/PiggyFactions#47]
Please put a translation of the plugin into the Brazilian language.

**Comment by KauaMCPE** [comment]
????? Help

**Comment by Aericio** [comment]
Yes, because I am suddenly bilingual.

**Comment by Aericio** [comment]
We are working on setting up Transifex, then we'll have support for multiple languages. Until then, no publicly available translations are out yet.

**Comment by Aericio** [comment]
We've setup a Transifex project. Please read contribution guidelines [here](https://github.com/DaPigGuy/PiggyFactions/blob/master/.github/CONTRIBUTING.md) if you want to contribute.

No translators have volunteered to do Brazilian, so there will not be translations for your language.
