### ISSUE TITLE
PureChat rank symbol

### ISSUE THREAD

**Issue by KareemDoesMc** [DaPigGuy/PiggyFactions#48]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyFactions
- * [ ] Have a detailed title.

### Issue Description
Well this really I don't know if this would be considered a bug but. I've been trying to change the tags to ** but all it shows is leader, member, recruit, by your factions name instead of **, *.

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### OS and Versions

* PocketMine-MP:
* PiggyFactions:
* PHP:
* Server OS:

### Extra Information

**Comment by Aericio** [comment]
Upload your configuration to https://hastebin.com/

**Comment by Thunter1** [comment]
its not cofiguration.. he want this plugin change the rolename in chat to symbol like from Leader -> **
its seem like a bug bcuz the purechat tag is like 

{fac_rank} | Faction rank symbol

But its not even a rank symbol

**Comment by Heisenburger69** [comment]
@Thunter1 Please use https://poggit.pmmp.io/r/88188/PureChat_dev-1.phar
