### ISSUE TITLE
Faction command does not implement PluginIdentifiableCommand

### ISSUE THREAD

**Issue by SOF3** [DaPigGuy/PiggyFactions#49]
This prevents Poggit from detecting the command, and hence the plugin cannot be searched.

**Comment by JackMD** [comment]
Shouldn't this be done by commando tho?

**Comment by SOF3** [comment]
Fun fact: Commando doesn't even take a Plugin instance, so they can't fix it without breaking BC.
https://github.com/CortexPE/Commando/blob/master/src/CortexPE/Commando/BaseCommand.php#L74-L78

I created https://github.com/CortexPE/Commando/issues/26 on Commando though.
