### ISSUE TITLE
Internal server error when doing /f claim

### ISSUE THREAD

**Issue by grepolis2c** [DaPigGuy/PiggyFactions#56]
Hi! We're encountering an issue regarding /f claim.
Every time we do /f claim we get an Internal server error
We're running pocketMine-MP 3.12.2 for Minecraft: Bedrock Edition v1.14.60 (protocol version 390) and I just recently updated to the latest version of piggy factions plugin v1.0.7

Steps to reproduce error:
1. Type /f claim
2. then I get internal server error

**Comment by Aericio** [comment]
Unable to reproduce.
