### ISSUE TITLE
Enderchests could be covered in the scope containers

### ISSUE THREAD

**Issue by ExileWeb** [DaPigGuy/PiggyFactions#57]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description
Enderchests should be included in the scope of the container permission, whereas they appear to default into the interaction permission. 

### Extra Information
Enderchests are ignored by the container permission.

**Comment by DaPigGuy** [comment]
Enderchests are not considered containers by PMMP as the inventory is by player and not by block
