### ISSUE TITLE
ScoreHud addon crash

### ISSUE THREAD

**Issue by PsychoPE** [DaPigGuy/PiggyFactions#61]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyFactions
- * [x] Have a detailed title.

Link to crashdump: 

https://pastebin.com/Snjyduvb

### Extra Information

**Comment by DaPigGuy** [comment]
Try the latest revision at https://gist.github.com/DaPigGuy/07442f8b98a70e5973a528e4516e35d1
