### ISSUE TITLE
Duplicate colum name money

### ISSUE THREAD

**Issue by UnEnanoMas** [DaPigGuy/PiggyFactions#66]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyFactions
- * [x] Have a detailed title.

### Issue Description

[12:24:36] [Server thread/INFO]: Enabling PiggyFactions v1.0.8
Warning: SQLite3::prepare(): Unable to prepare statement: 1, duplicate column name: money in phar:///home/container/plugins/PiggyFactions_dev-103.phar/src/DaPigGuy/PiggyFactions/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 79
Warning: SQLite3::prepare(): Unable to prepare statement: 1, duplicate column name: language in phar:///home/container/plugins/PiggyFactions_dev-103.phar/src/DaPigGuy/PiggyFactions/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 79
Warning: SQLite3::prepare(): Unable to prepare statement: 1, duplicate column name: powerboost in phar:///home/container/plugins/PiggyFactions_dev-103.phar/src/DaPigGuy/PiggyFactions/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 79
Warning: SQLite3::prepare(): Unable to prepare statement: 1, duplicate column name: powerboost in phar:///home/container/plugins/PiggyFactions_dev-103.phar/src/DaPigGuy/PiggyFactions/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 79

#### Steps to Reproduce the Issue
1. Install the plugin
2. Restart your server

### OS and Versions

* PocketMine-MP: Latest
* PiggyFactions: Latest
* PHP: ¿?
* Server OS: ¿?

### Extra Information

**Comment by Aericio** [comment]
Just restart your server again.
