### ISSUE TITLE
It says you are not in Faction

### ISSUE THREAD

**Issue by ganeshbista209** [DaPigGuy/PiggyFactions#67]
I kept my spawn world as blacklisted and when i tp to my other world called faction and once i click on claim it says you are not in Faction.
Why is it happening?

I use plugin
Vanilla enchant
PureEntitiesX
Teaspoon

And if any of this plugin is creating a problem please let me  know.

**Comment by Aericio** [comment]
Did you create a faction? Not sure what you mean.
