### ISSUE TITLE
How does overclaiming work?

### ISSUE THREAD

**Issue by NormalOcean6686** [DaPigGuy/PiggyFactions#68]
Can u please add the ability to over claim another faction if the faction has more power please

**Comment by Aericio** [comment]
Overclaiming is allowed if the faction's total land claims exceed their current power. You need to create a starting claim on the border of the land you're trying to overclaim, and from that you gradually overclaim into their land.
![image](https://user-images.githubusercontent.com/16523741/84732026-4b9e9400-af36-11ea-8ce2-76e7b86d90d3.png)

A documentation of our claiming system, which is literally the same as Java's MassiveCraft Factions, is in the works of being created.

**Comment by NormalOcean6686** [comment]
K thx. Ppl been woundering this on my server and all i could say idk
