### ISSUE TITLE
PureChat support

### ISSUE THREAD

**Issue by jaylac2000** [DaPigGuy/PiggyFactions#7]
this already looks better than FactionsPro . I might switch to this in my next season 

but can you make a ScoreHud addon & PureChat support? 

ScoreHud addon
- {factionmembers} - shows amt of members like 2, 3, 4 etc
- {faction} - gets faction name
- {factionrank} - gets players rank in the faction. leader, officer etc

Purechat: 
{faction} - gets faction name

add max amt of faction members 

add more configurable opens like FactionsPro

**Comment by minijaham** [comment]
^ to add something to that

Scorehud: {faction} and {faction_power}

Purechat: {fac_name} {fac_rank} and maybe {fac_power}

**Comment by jaylac2000** [comment]
ah ok ty @minijaham

**Comment by DaPigGuy** [comment]
https://gist.github.com/DaPigGuy/07442f8b98a70e5973a528e4516e35d1

**Comment by jaylac2000** [comment]
tyty this pl already better than FactionsPro

**Comment by Thunder33345** [comment]
will we do purechat?
it's a hell to deal with...
also you could had get tag manager and do it that way

**Comment by jaylac2000** [comment]
my purechat is already forked for my server so if yall do it ill have to copy / paste the code in

other wise u should look info "prisons essentials" plugin and add config like

chat: &7{faction} {defaultformat}

or whatever

**Comment by DaPigGuy** [comment]
https://github.com/poggit-orphanage/PureChat/pull/32
