### ISSUE TITLE
Plugin API is not working onEnable

### ISSUE THREAD

**Issue by dadodasyra** [DaPigGuy/PiggyFactions#76]
Please make sure your issue complies with these guidelines:
- * [X] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [X] Issue must have not been reported previously
- * [X] Make sure you are on the latest version of PMMP & PiggyFactions
- * [/] Have a detailed title.

### Issue Description

- Expected result: To be able to access information from the API of the plugin via another plugin on the onEnable
- Actual result: An error saying that the function does not return anything when it is supposed to return the instance of X class

#### Steps to Reproduce the Issue
1. Get plugin in another plugin like this :

> `        /** @var PiggyFactions $pigfaction */
>         $pigfaction = $this->getServer()->getPluginManager()->getPlugin("PiggyFactions");
>         $this->faction = $pigfaction->getFactionsManager();
>         $this->claims = $pigfaction->getClaimsManager();`

2. As soon as php reads `$pigfaction->getFactionsManager()`
There will be an error on the console. The error:
` [19:15:45] [Server thread/CRITICAL]: TypeError: "Return value of DaPigGuy\PiggyFactions\PiggyFactions::getFactionsManager() must be an instance of DaPigGuy\PiggyFactions\factions\FactionsManager, null returned" (EXCEPTION) in "plugins/PiggyFactions/src/DaPigGuy/PiggyFactions/PiggyFactions" at line 179`

### OS and Versions

* PocketMine-MP: 3.14.2
* PiggyFactions: 1.1.1
* PHP: 7
* Server OS: Debian 10

### Extra Information
This is a bug, but it is surely not caused by the plugin itself but the way pocketmine works.
I don't know if there is anything you can do about it.

**Comment by Aericio** [comment]
Try latest dev build from Poggit-CI
