### ISSUE TITLE
Internal Server Error when adding the {fac_name} and {fac_rank} format tags.

### ISSUE THREAD

**Issue by CrafterLTU** [DaPigGuy/PiggyFactions#79]
Issue Description.

- Expected result: Rank formats work as they intend to, '&7[&l&6Newcomer&r&7] &6[{fac_name}][{fac_rank}] &7{display_name} &7>> {msg}' or at least making sure {fac_name} and {fac_rank} work.

- Actual result: When reloading or joining the server, it gives off an Internal Server error, even if all the virions and the pr-15 purechat was added (except libPiggyEconomy cuz it was outdated and didn't register)

#### Steps to Reproduce the Issue
1. Try and download the PiggyFactions latest release, download all the virions and the purechat pr-15 release;
2. in purechat config, set default-factions-plugin to PiggyFactions;
3. set the Guest group to:
  Guest:
    chat: '&7[&l&6Newcomer&r&7] &6[{fac_name}][{fac_rank}] &7{display_name} &7>> {msg}'
    nametag: '&7[&l&6Newcomer&r&7] &6[{fac_name}][{fac_rank}] &7{display_name}'
(Or anything just make sure to add {fac_name} and/or {fac_rank};
4. reload/restart the server.

### OS and Versions

* PocketMine-MP: 3.15.0 (protocol version 408)
* PiggyFactions: 1.1.1
* PHP: PHP 7.3 (i believe)
* Server OS: CentOS 64-Bit Linux (i think. im hosting on apexminecrafthosting)

Whenever i set the default-factions-plugin to PiggyFactions it gives the player an ''Internal Server Error'' every time they type something in the chat, or when any player joins it instantly shows up with an ''Internal Server Error''.
If theres anything else, please ask, ill try to provide with as much information to my knowladge.
heres a hastebin with the error too
https://hastebin.com/gipifarube.bash

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyFactions#purechat-tags

Update your version of PureChat
