### ISSUE TITLE
Enable TNT explosions in claims

### ISSUE THREAD

**Issue by Centoller** [DaPigGuy/PiggyFactions#85]
Please make sure your issue complies with these guidelines:
- * [ *] Idea must have not been suggested previously
- * [ *] Be detailed on what you want & make sure the idea is plausible

### Description

My suggestion is that the /f claim works like the wand, so choose where to protect from, since the current system is difficult for most players

or make it like the economyland

also that the tnt does not break the protection, as it happens in FactionsPro so have it active

**Comment by Aericio** [comment]
Suggestion 1 denied, there is `/f claim auto` and `/f seechunks`. We won't change to whatever economyland does.

I don't know how TNT is currently, so will look into that.
