### ISSUE TITLE
Faction members not being fully kicked, and error upon commands like /f kick, /f leave and /f ban

### ISSUE THREAD

**Issue by RKAbdul** [DaPigGuy/PiggyFactions#88]
Please make sure your issue complies with these guidelines:.
- * [✓] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [✓] Issue must have not been reported previously
- * [✓] Make sure you are on the latest version of PMMP & PiggyFactions
- * [✓] Have a detailed title.

When Factions leader try to kick a player, if the player is possibly offline. It will kick the player by his side, meaning that for the player when does faction commands it will give him no faction msg. But the player is still included in the factions info and his power is still added to the *Faction Power*
I joined the faction use */f admin* and tried to kick the same player again and this the *[Error](https://hastebin.com/puhulihoci.coffeescript)*
The same error would occur when leaving the faction, or banning the same player

- Expected result: What were you expecting to happen?
- That the player should be kicked by the Faction and ofc completely get removed by the faction
- Actual result: What actually happened?
The player got kicked by his side, but when doing /f info again it will show the player name but without any sign of any rank like recruit...
#### Steps to Reproduce the Issue
1. Kick a member when he is offline
2. Do /f info
3- Try to kick the same player again

### OS and Versions

* PocketMine-MP: 3.15.0
* PiggyFactions: 1.1.2
* PHP:
* Server OS:

### Extra Information
I would also request, to fix /f home
And to fix these issues possibly soon 👍

**Comment by Aericio** [comment]
Unable to reproduce.
![image](https://user-images.githubusercontent.com/16523741/97948918-12748e00-1d36-11eb-86e6-4ab3254426c7.png)
