### ISSUE TITLE
/f hud

### ISSUE THREAD

**Issue by litter295** [DaPigGuy/PiggyFactions#9]
Add a /f hud command similar to Faction PE's f hud that shows the faction you're in and the amount of money you currently. Also if possible can you link the money with EconomyAPI Or "PiggyEconomy" 
![OnPaste 20200507-033754](https://user-images.githubusercontent.com/62941505/81248437-45062e00-9014-11ea-9af9-bd5c2041a877.png)

**Comment by Johnsonk79** [comment]
Could be easily done by yourself with any hud plugin

**Comment by DaPigGuy** [comment]
We are unlikely to add this directly into PiggyFactions. If you can provide a link to an HUD plugin available on Poggit, we can add support for PiggyFactions to it. Do note that we have a ScoreHUD addon (link in README)
