### ISSUE TITLE
ISE if submitted form input is empty

### ISSUE THREAD

**Issue by UnEnanoMas** [DaPigGuy/PiggyFactions#91]
Please make sure your issue complies with these guidelines:
- * [*] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [*] Issue must have not been reported previously
- * [*] Make sure you are on the latest version of PMMP & PiggyFactions
- * [*] Have a detailed title.

Link to crashdump: (It did not let me use the page well to crash)
[Crash.txt](https://github.com/DaPigGuy/PiggyFactions/files/5293284/Crash.txt)

### Extra Information

**Comment by Aericio** [comment]
![image](https://user-images.githubusercontent.com/16523741/97952002-1c9b8a00-1d40-11eb-8e95-6e3b9c459e12.png)

Used UI and command, worked fine.
