### ISSUE TITLE
Deny /f fly if you are creative

### ISSUE THREAD

**Issue by UnEnanoMas** [DaPigGuy/PiggyFactions#92]
Please make sure your issue complies with these guidelines:
- * [*] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [*] Issue must have not been reported previously
- * [*] Make sure you are on the latest version of PMMP & PiggyFactions
- * [*] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
**That when I activated the fly in creative mode, it gave me a warning like "you cannot activate the flight in creative mode"**
- Actual result: What actually happened?
**Activate the flight**

#### Steps to Reproduce the Issue
1. /gamemode 1
2. /f fly

### OS and Versions

* PocketMine-MP: 3.15.1
* PiggyFactions: Dev #126
* PHP: 7
* Server OS: Windows 10

### Extra Information

**Comment by Thunder33345** [comment]
why? what's wrong with f fly in creative?

**Comment by UnEnanoMas** [comment]
It makes no sense to activate the fly when you are creative

**Comment by Aericio** [comment]
This isn't really a bug, more of an enhancement. Not really a priority, just don't use the command if you're in creative...
