### ISSUE TITLE
Faction being attacked

### ISSUE THREAD

**Issue by deuhd** [DaPigGuy/PiggyFactions#95]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

When a TNT explode inside a claim the faction will be in "beeing attacked" mode and Fly will be disable, the fac will not be in attack anymore if in 3 min there is no more explosion inside the claim.

**Comment by Aericio** [comment]
@deuhd is this a feature request?
