### ISSUE TITLE
Piggy Factions

### ISSUE THREAD

**Issue by nezneb0** [DaPigGuy/PiggyFactions#98]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description
The Factions sould only work on a pacific world.

### Extra Information
When someone trys to use commands in unsupported world it will say "You're not in Factions"

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyFactions/blob/master/resources/config.yml#L40

Add worlds you don't want people claiming in to the blacklist.
